<#
.SYNOPSIS
    Creates a GitHub release whose asset is a publish.zip containing placeholder.txt.

.DESCRIPTION
    Builds a publish.zip archive containing a single placeholder.txt file, then
    creates a GitHub release and attaches the archive as an asset named
    publish.zip. If the tag does not exist yet, gh creates it together with the
    release (atomic), which keeps the release bound to the tag instead of an
    auto-generated "untagged" ref.

    The release workflow (.github/workflows/upload-nexusmods.yml) triggers on
    "release: published". To avoid firing the Nexus Mods upload, the release is
    created as a DRAFT by default. Pass -Publish to create a published release.

.PARAMETER Tag
    Release tag. Defaults to v0.0.0.

.PARAMETER Repo
    Repository in owner/name form. Defaults to the origin remote of this repo.

.PARAMETER Publish
    Create a published release (triggers the upload workflow). Default is draft.

.PARAMETER Prerelease
    Mark the release as a prerelease.

.PARAMETER Title
    Release title. Defaults to the tag.

.PARAMETER Notes
    Release notes. Defaults to a generated placeholder message.

.EXAMPLE
    .\create-release.ps1
    Creates a draft v0.0.0 release with a publish.zip placeholder asset.

.EXAMPLE
    .\create-release.ps1 -Tag v0.1.0 -Publish
    Creates a published v0.1.0 release (triggers the upload workflow).
#>
[CmdletBinding()]
param(
    [string]$Tag = "v0.0.0",
    [string]$Repo,
    [switch]$Publish,
    [switch]$Prerelease,
    [string]$Title,
    [string]$Notes
)

$ErrorActionPreference = "Stop"

# --- Preflight: gh CLI installed and authenticated ---
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    throw "The GitHub CLI (gh) was not found on PATH. Install it from https://cli.github.com/"
}
# Invoke gh via cmd /c: under $ErrorActionPreference = "Stop", a native command
# writing to stderr is treated as a terminating error even with 2>$null or
# *>&1, which breaks the auth check below. cmd /c avoids that. Judge with $?.
& cmd /c "gh auth status >nul 2>nul"
if (-not $?) {
    throw "You are not authenticated with gh. Run 'gh auth login' first."
}

# --- Resolve repository (owner/name) ---
if (-not $Repo) {
    $origin = & git -C $PSScriptRoot remote get-url origin 2>$null
    if ($origin -match 'github\.com[:/](?<repo>[^/]+/[^/]+?)(?:\.git)?/?$') {
        $Repo = $Matches['repo']
    }
}
if (-not $Repo) {
    throw "Could not determine the repository. Pass -Repo owner/name explicitly."
}

Write-Host "Repository : $Repo"
Write-Host "Tag        : $Tag"
Write-Host "Mode       : $(if ($Publish) { 'published' } else { 'draft' })"

# --- Fail fast if a release already exists for this tag ---
# Use cmd /c so a "release not found" (gh writes it to stderr) does not become a
# terminating error under $ErrorActionPreference = "Stop". Judge success with $?.
& cmd /c "gh release view `"$Tag`" --repo `"$Repo`" --json tagName >nul 2>nul"
if ($?) {
    throw "A release for tag '$Tag' already exists in $Repo. Delete it first or pick another tag."
}

# --- Build publish.zip containing placeholder.txt ---
$work = Join-Path ([System.IO.Path]::GetTempPath()) ("create-release-" + [System.Guid]::NewGuid().ToString("N"))
$pkg = Join-Path $work "pkg"
$zip = Join-Path $work "publish.zip"
New-Item -ItemType Directory -Path $pkg -Force | Out-Null
try {
    $placeholder = @"
Placeholder package for release $Tag.
"@
    # Write UTF-8 without a BOM so downstream tools read the file cleanly.
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText((Join-Path $pkg "placeholder.txt"), $placeholder, $utf8NoBom)

    Compress-Archive -Path (Join-Path $pkg "*") -DestinationPath $zip -Force
    $zipSize = (Get-Item $zip).Length
    Write-Host "Built      : publish.zip ($zipSize bytes) containing placeholder.txt"

    # --- Create the release (gh creates the tag if missing, binding atomically) ---
    if (-not $Title) { $Title = $Tag }
    if (-not $Notes) {
        $Notes = "Release $Tag.`n`nThe publish.zip asset is a placeholder build generated by create-release.ps1."
    }

    $ghArgs = @("release", "create", $Tag, $zip, "--repo", $Repo, "--title", $Title, "--notes", $Notes)
    if (-not $Publish) { $ghArgs += "--draft" }
    if ($Prerelease) { $ghArgs += "--prerelease" }

    & gh @ghArgs
    if ($LASTEXITCODE -ne 0) {
        throw "gh release create failed with exit code $LASTEXITCODE."
    }

    # --- Verify and report ---
    # gh prints an "untagged-<sha>" URL for draft releases created without a
    # pushed tag; that is only a display artifact. The authoritative fields are
    # tagName and targetCommitish, so report those instead of the URL.
    $info = & gh release view $Tag --repo $Repo --json tagName, targetCommitish, isDraft, assets | ConvertFrom-Json
    Write-Host ""
    Write-Host ("Tag        : " + $info.tagName + "  (target: " + $info.targetCommitish + ")")
    Write-Host ("Draft      : " + $info.isDraft)
    $asset = $info.assets | Where-Object { $_.name -eq "publish.zip" }
    if ($asset) {
        Write-Host ("Asset      : publish.zip (" + $asset.size + " bytes)")
    }
    else {
        Write-Warning "publish.zip was not found among the release assets."
    }
    if (-not $Publish) {
        Write-Host ""
        Write-Host "NOTE: the release is a DRAFT and did NOT trigger the upload workflow." -ForegroundColor Yellow
        Write-Host "      Publishing it (or re-running with -Publish) triggers the Nexus Mods upload." -ForegroundColor Yellow
    }
}
finally {
    Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue
}
